import { BaseEntity } from "@common/database/base.entity";
import { Column, Entity, Index, JoinColumn, ManyToOne } from "typeorm";

import { IArticle } from "../interfaces/article.interface";
import { User } from "./user.entity";

@Entity("articles")
export class Article extends BaseEntity implements IArticle {
	@Column({ type: "varchar", length: 255, nullable: false })
	title!: string;

	@Column({ type: "text", nullable: false })
	description!: string;

	// Note: usually the createdAt field is enough for publication date record.
	// Usually publication date must be immutable and autogenerated when
	// user/author creates an article.
	// But to follow the test project requirements I declared publishedAt field.
	@Index()
	@Column({ type: "timestamp", nullable: true })
	publishedAt!: Date | null;

	@Index()
	@Column({ type: "uuid", name: "author_id", nullable: false })
	authorId!: string;

	// Note: Again, best practice is not to use User directly in article
	// logic, but create a separate Author entity for the relation
	// to the Article entity.
	// But in the description of the test project it is not stated explicitly
	// to create Author entity.
	@ManyToOne(() => User, (user) => user.articles, { eager: false, onDelete: "CASCADE" })
	@JoinColumn({ name: "author_id" })
	author!: User;
}
